/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as NewsRouteImport } from './routes/news'
import { Route as BleedingDisordersFaqsRouteImport } from './routes/bleeding-disorders/faqs'
import { Route as BleedingDisordersHaemophiliaRouteImport } from './routes/bleeding-disorders/haemophilia'
import { Route as BleedingDisordersInhibitorsRouteImport } from './routes/bleeding-disorders/inhibitors'
import { Route as BleedingDisordersTreatmentCentresRouteImport } from './routes/bleeding-disorders/treatment-centres'
import { Route as BleedingDisordersTreatmentTypesRouteImport } from './routes/bleeding-disorders/treatment-types'
import { Route as BleedingDisordersWomenWithBleedingDisordersRouteImport } from './routes/bleeding-disorders/women-with-bleeding-disorders'
import { Route as EventsCategoriesRouteImport } from './routes/events/categories'
import { Route as GetInvolvedFundraisingRouteImport } from './routes/get-involved/fundraising'
import { Route as GetInvolvedJoinRouteImport } from './routes/get-involved/join'
import { Route as PublicInquiryInquiryNewsRouteImport } from './routes/public-inquiry/inquiry-news'
import { Route as PublicInquirySupportRouteImport } from './routes/public-inquiry/support'
import { Route as ResourcesExternalResourcesRouteImport } from './routes/resources/external-resources'
import { Route as ResourcesGuidelinesRouteImport } from './routes/resources/guidelines'
import { Route as ResourcesPublicationsRouteImport } from './routes/resources/publications'
import { Route as ResourcesVideosRouteImport } from './routes/resources/videos'
import { Route as SupportDayDayLivingRouteImport } from './routes/support/day-day-living'
import { Route as SupportNewlyDiagnosedRouteImport } from './routes/support/newly-diagnosed'
import { Route as SupportOurCommunityRouteImport } from './routes/support/our-community'
import { Route as PublicInquiryTheInfectedBloodInquiryIndexRouteImport } from './routes/public-inquiry/the-infected-blood-inquiry/index'
import { Route as PublicInquiryTheInfectedBloodInquiryAppgRouteImport } from './routes/public-inquiry/the-infected-blood-inquiry/appg'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const BleedingDisordersFaqsRoute = BleedingDisordersFaqsRouteImport.update({
  id: '/bleeding-disorders/faqs',
  path: '/bleeding-disorders/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const BleedingDisordersHaemophiliaRoute =
  BleedingDisordersHaemophiliaRouteImport.update({
    id: '/bleeding-disorders/haemophilia',
    path: '/bleeding-disorders/haemophilia',
    getParentRoute: () => rootRouteImport,
  } as any)
const BleedingDisordersInhibitorsRoute =
  BleedingDisordersInhibitorsRouteImport.update({
    id: '/bleeding-disorders/inhibitors',
    path: '/bleeding-disorders/inhibitors',
    getParentRoute: () => rootRouteImport,
  } as any)
const BleedingDisordersTreatmentCentresRoute =
  BleedingDisordersTreatmentCentresRouteImport.update({
    id: '/bleeding-disorders/treatment-centres',
    path: '/bleeding-disorders/treatment-centres',
    getParentRoute: () => rootRouteImport,
  } as any)
const BleedingDisordersTreatmentTypesRoute =
  BleedingDisordersTreatmentTypesRouteImport.update({
    id: '/bleeding-disorders/treatment-types',
    path: '/bleeding-disorders/treatment-types',
    getParentRoute: () => rootRouteImport,
  } as any)
const BleedingDisordersWomenWithBleedingDisordersRoute =
  BleedingDisordersWomenWithBleedingDisordersRouteImport.update({
    id: '/bleeding-disorders/women-with-bleeding-disorders',
    path: '/bleeding-disorders/women-with-bleeding-disorders',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsCategoriesRoute = EventsCategoriesRouteImport.update({
  id: '/events/categories',
  path: '/events/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedFundraisingRoute = GetInvolvedFundraisingRouteImport.update({
  id: '/get-involved/fundraising',
  path: '/get-involved/fundraising',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedJoinRoute = GetInvolvedJoinRouteImport.update({
  id: '/get-involved/join',
  path: '/get-involved/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicInquiryInquiryNewsRoute =
  PublicInquiryInquiryNewsRouteImport.update({
    id: '/public-inquiry/inquiry-news',
    path: '/public-inquiry/inquiry-news',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicInquirySupportRoute = PublicInquirySupportRouteImport.update({
  id: '/public-inquiry/support',
  path: '/public-inquiry/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesExternalResourcesRoute =
  ResourcesExternalResourcesRouteImport.update({
    id: '/resources/external-resources',
    path: '/resources/external-resources',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesGuidelinesRoute = ResourcesGuidelinesRouteImport.update({
  id: '/resources/guidelines',
  path: '/resources/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesPublicationsRoute = ResourcesPublicationsRouteImport.update({
  id: '/resources/publications',
  path: '/resources/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesVideosRoute = ResourcesVideosRouteImport.update({
  id: '/resources/videos',
  path: '/resources/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportDayDayLivingRoute = SupportDayDayLivingRouteImport.update({
  id: '/support/day-day-living',
  path: '/support/day-day-living',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportNewlyDiagnosedRoute = SupportNewlyDiagnosedRouteImport.update({
  id: '/support/newly-diagnosed',
  path: '/support/newly-diagnosed',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportOurCommunityRoute = SupportOurCommunityRouteImport.update({
  id: '/support/our-community',
  path: '/support/our-community',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicInquiryTheInfectedBloodInquiryIndexRoute =
  PublicInquiryTheInfectedBloodInquiryIndexRouteImport.update({
    id: '/public-inquiry/the-infected-blood-inquiry/',
    path: '/public-inquiry/the-infected-blood-inquiry/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicInquiryTheInfectedBloodInquiryAppgRoute =
  PublicInquiryTheInfectedBloodInquiryAppgRouteImport.update({
    id: '/public-inquiry/the-infected-blood-inquiry/appg',
    path: '/public-inquiry/the-infected-blood-inquiry/appg',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/news': typeof NewsRoute
  '/bleeding-disorders/faqs': typeof BleedingDisordersFaqsRoute
  '/bleeding-disorders/haemophilia': typeof BleedingDisordersHaemophiliaRoute
  '/bleeding-disorders/inhibitors': typeof BleedingDisordersInhibitorsRoute
  '/bleeding-disorders/treatment-centres': typeof BleedingDisordersTreatmentCentresRoute
  '/bleeding-disorders/treatment-types': typeof BleedingDisordersTreatmentTypesRoute
  '/bleeding-disorders/women-with-bleeding-disorders': typeof BleedingDisordersWomenWithBleedingDisordersRoute
  '/events/categories': typeof EventsCategoriesRoute
  '/get-involved/fundraising': typeof GetInvolvedFundraisingRoute
  '/get-involved/join': typeof GetInvolvedJoinRoute
  '/public-inquiry/inquiry-news': typeof PublicInquiryInquiryNewsRoute
  '/public-inquiry/support': typeof PublicInquirySupportRoute
  '/resources/external-resources': typeof ResourcesExternalResourcesRoute
  '/resources/guidelines': typeof ResourcesGuidelinesRoute
  '/resources/publications': typeof ResourcesPublicationsRoute
  '/resources/videos': typeof ResourcesVideosRoute
  '/support/day-day-living': typeof SupportDayDayLivingRoute
  '/support/newly-diagnosed': typeof SupportNewlyDiagnosedRoute
  '/support/our-community': typeof SupportOurCommunityRoute
  '/public-inquiry/the-infected-blood-inquiry/appg': typeof PublicInquiryTheInfectedBloodInquiryAppgRoute
  '/public-inquiry/the-infected-blood-inquiry/': typeof PublicInquiryTheInfectedBloodInquiryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/news': typeof NewsRoute
  '/bleeding-disorders/faqs': typeof BleedingDisordersFaqsRoute
  '/bleeding-disorders/haemophilia': typeof BleedingDisordersHaemophiliaRoute
  '/bleeding-disorders/inhibitors': typeof BleedingDisordersInhibitorsRoute
  '/bleeding-disorders/treatment-centres': typeof BleedingDisordersTreatmentCentresRoute
  '/bleeding-disorders/treatment-types': typeof BleedingDisordersTreatmentTypesRoute
  '/bleeding-disorders/women-with-bleeding-disorders': typeof BleedingDisordersWomenWithBleedingDisordersRoute
  '/events/categories': typeof EventsCategoriesRoute
  '/get-involved/fundraising': typeof GetInvolvedFundraisingRoute
  '/get-involved/join': typeof GetInvolvedJoinRoute
  '/public-inquiry/inquiry-news': typeof PublicInquiryInquiryNewsRoute
  '/public-inquiry/support': typeof PublicInquirySupportRoute
  '/resources/external-resources': typeof ResourcesExternalResourcesRoute
  '/resources/guidelines': typeof ResourcesGuidelinesRoute
  '/resources/publications': typeof ResourcesPublicationsRoute
  '/resources/videos': typeof ResourcesVideosRoute
  '/support/day-day-living': typeof SupportDayDayLivingRoute
  '/support/newly-diagnosed': typeof SupportNewlyDiagnosedRoute
  '/support/our-community': typeof SupportOurCommunityRoute
  '/public-inquiry/the-infected-blood-inquiry/appg': typeof PublicInquiryTheInfectedBloodInquiryAppgRoute
  '/public-inquiry/the-infected-blood-inquiry': typeof PublicInquiryTheInfectedBloodInquiryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/news': typeof NewsRoute
  '/bleeding-disorders/faqs': typeof BleedingDisordersFaqsRoute
  '/bleeding-disorders/haemophilia': typeof BleedingDisordersHaemophiliaRoute
  '/bleeding-disorders/inhibitors': typeof BleedingDisordersInhibitorsRoute
  '/bleeding-disorders/treatment-centres': typeof BleedingDisordersTreatmentCentresRoute
  '/bleeding-disorders/treatment-types': typeof BleedingDisordersTreatmentTypesRoute
  '/bleeding-disorders/women-with-bleeding-disorders': typeof BleedingDisordersWomenWithBleedingDisordersRoute
  '/events/categories': typeof EventsCategoriesRoute
  '/get-involved/fundraising': typeof GetInvolvedFundraisingRoute
  '/get-involved/join': typeof GetInvolvedJoinRoute
  '/public-inquiry/inquiry-news': typeof PublicInquiryInquiryNewsRoute
  '/public-inquiry/support': typeof PublicInquirySupportRoute
  '/resources/external-resources': typeof ResourcesExternalResourcesRoute
  '/resources/guidelines': typeof ResourcesGuidelinesRoute
  '/resources/publications': typeof ResourcesPublicationsRoute
  '/resources/videos': typeof ResourcesVideosRoute
  '/support/day-day-living': typeof SupportDayDayLivingRoute
  '/support/newly-diagnosed': typeof SupportNewlyDiagnosedRoute
  '/support/our-community': typeof SupportOurCommunityRoute
  '/public-inquiry/the-infected-blood-inquiry/appg': typeof PublicInquiryTheInfectedBloodInquiryAppgRoute
  '/public-inquiry/the-infected-blood-inquiry/': typeof PublicInquiryTheInfectedBloodInquiryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/news'
    | '/bleeding-disorders/faqs'
    | '/bleeding-disorders/haemophilia'
    | '/bleeding-disorders/inhibitors'
    | '/bleeding-disorders/treatment-centres'
    | '/bleeding-disorders/treatment-types'
    | '/bleeding-disorders/women-with-bleeding-disorders'
    | '/events/categories'
    | '/get-involved/fundraising'
    | '/get-involved/join'
    | '/public-inquiry/inquiry-news'
    | '/public-inquiry/support'
    | '/resources/external-resources'
    | '/resources/guidelines'
    | '/resources/publications'
    | '/resources/videos'
    | '/support/day-day-living'
    | '/support/newly-diagnosed'
    | '/support/our-community'
    | '/public-inquiry/the-infected-blood-inquiry/appg'
    | '/public-inquiry/the-infected-blood-inquiry/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/news'
    | '/bleeding-disorders/faqs'
    | '/bleeding-disorders/haemophilia'
    | '/bleeding-disorders/inhibitors'
    | '/bleeding-disorders/treatment-centres'
    | '/bleeding-disorders/treatment-types'
    | '/bleeding-disorders/women-with-bleeding-disorders'
    | '/events/categories'
    | '/get-involved/fundraising'
    | '/get-involved/join'
    | '/public-inquiry/inquiry-news'
    | '/public-inquiry/support'
    | '/resources/external-resources'
    | '/resources/guidelines'
    | '/resources/publications'
    | '/resources/videos'
    | '/support/day-day-living'
    | '/support/newly-diagnosed'
    | '/support/our-community'
    | '/public-inquiry/the-infected-blood-inquiry/appg'
    | '/public-inquiry/the-infected-blood-inquiry'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/news'
    | '/bleeding-disorders/faqs'
    | '/bleeding-disorders/haemophilia'
    | '/bleeding-disorders/inhibitors'
    | '/bleeding-disorders/treatment-centres'
    | '/bleeding-disorders/treatment-types'
    | '/bleeding-disorders/women-with-bleeding-disorders'
    | '/events/categories'
    | '/get-involved/fundraising'
    | '/get-involved/join'
    | '/public-inquiry/inquiry-news'
    | '/public-inquiry/support'
    | '/resources/external-resources'
    | '/resources/guidelines'
    | '/resources/publications'
    | '/resources/videos'
    | '/support/day-day-living'
    | '/support/newly-diagnosed'
    | '/support/our-community'
    | '/public-inquiry/the-infected-blood-inquiry/appg'
    | '/public-inquiry/the-infected-blood-inquiry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NewsRoute: typeof NewsRoute
  BleedingDisordersFaqsRoute: typeof BleedingDisordersFaqsRoute
  BleedingDisordersHaemophiliaRoute: typeof BleedingDisordersHaemophiliaRoute
  BleedingDisordersInhibitorsRoute: typeof BleedingDisordersInhibitorsRoute
  BleedingDisordersTreatmentCentresRoute: typeof BleedingDisordersTreatmentCentresRoute
  BleedingDisordersTreatmentTypesRoute: typeof BleedingDisordersTreatmentTypesRoute
  BleedingDisordersWomenWithBleedingDisordersRoute: typeof BleedingDisordersWomenWithBleedingDisordersRoute
  EventsCategoriesRoute: typeof EventsCategoriesRoute
  GetInvolvedFundraisingRoute: typeof GetInvolvedFundraisingRoute
  GetInvolvedJoinRoute: typeof GetInvolvedJoinRoute
  PublicInquiryInquiryNewsRoute: typeof PublicInquiryInquiryNewsRoute
  PublicInquirySupportRoute: typeof PublicInquirySupportRoute
  ResourcesExternalResourcesRoute: typeof ResourcesExternalResourcesRoute
  ResourcesGuidelinesRoute: typeof ResourcesGuidelinesRoute
  ResourcesPublicationsRoute: typeof ResourcesPublicationsRoute
  ResourcesVideosRoute: typeof ResourcesVideosRoute
  SupportDayDayLivingRoute: typeof SupportDayDayLivingRoute
  SupportNewlyDiagnosedRoute: typeof SupportNewlyDiagnosedRoute
  SupportOurCommunityRoute: typeof SupportOurCommunityRoute
  PublicInquiryTheInfectedBloodInquiryAppgRoute: typeof PublicInquiryTheInfectedBloodInquiryAppgRoute
  PublicInquiryTheInfectedBloodInquiryIndexRoute: typeof PublicInquiryTheInfectedBloodInquiryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bleeding-disorders/faqs': {
      id: '/bleeding-disorders/faqs'
      path: '/bleeding-disorders/faqs'
      fullPath: '/bleeding-disorders/faqs'
      preLoaderRoute: typeof BleedingDisordersFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bleeding-disorders/haemophilia': {
      id: '/bleeding-disorders/haemophilia'
      path: '/bleeding-disorders/haemophilia'
      fullPath: '/bleeding-disorders/haemophilia'
      preLoaderRoute: typeof BleedingDisordersHaemophiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bleeding-disorders/inhibitors': {
      id: '/bleeding-disorders/inhibitors'
      path: '/bleeding-disorders/inhibitors'
      fullPath: '/bleeding-disorders/inhibitors'
      preLoaderRoute: typeof BleedingDisordersInhibitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bleeding-disorders/treatment-centres': {
      id: '/bleeding-disorders/treatment-centres'
      path: '/bleeding-disorders/treatment-centres'
      fullPath: '/bleeding-disorders/treatment-centres'
      preLoaderRoute: typeof BleedingDisordersTreatmentCentresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bleeding-disorders/treatment-types': {
      id: '/bleeding-disorders/treatment-types'
      path: '/bleeding-disorders/treatment-types'
      fullPath: '/bleeding-disorders/treatment-types'
      preLoaderRoute: typeof BleedingDisordersTreatmentTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bleeding-disorders/women-with-bleeding-disorders': {
      id: '/bleeding-disorders/women-with-bleeding-disorders'
      path: '/bleeding-disorders/women-with-bleeding-disorders'
      fullPath: '/bleeding-disorders/women-with-bleeding-disorders'
      preLoaderRoute: typeof BleedingDisordersWomenWithBleedingDisordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/categories': {
      id: '/events/categories'
      path: '/events/categories'
      fullPath: '/events/categories'
      preLoaderRoute: typeof EventsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/fundraising': {
      id: '/get-involved/fundraising'
      path: '/get-involved/fundraising'
      fullPath: '/get-involved/fundraising'
      preLoaderRoute: typeof GetInvolvedFundraisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/join': {
      id: '/get-involved/join'
      path: '/get-involved/join'
      fullPath: '/get-involved/join'
      preLoaderRoute: typeof GetInvolvedJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-inquiry/inquiry-news': {
      id: '/public-inquiry/inquiry-news'
      path: '/public-inquiry/inquiry-news'
      fullPath: '/public-inquiry/inquiry-news'
      preLoaderRoute: typeof PublicInquiryInquiryNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-inquiry/support': {
      id: '/public-inquiry/support'
      path: '/public-inquiry/support'
      fullPath: '/public-inquiry/support'
      preLoaderRoute: typeof PublicInquirySupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/external-resources': {
      id: '/resources/external-resources'
      path: '/resources/external-resources'
      fullPath: '/resources/external-resources'
      preLoaderRoute: typeof ResourcesExternalResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/guidelines': {
      id: '/resources/guidelines'
      path: '/resources/guidelines'
      fullPath: '/resources/guidelines'
      preLoaderRoute: typeof ResourcesGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/publications': {
      id: '/resources/publications'
      path: '/resources/publications'
      fullPath: '/resources/publications'
      preLoaderRoute: typeof ResourcesPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/videos': {
      id: '/resources/videos'
      path: '/resources/videos'
      fullPath: '/resources/videos'
      preLoaderRoute: typeof ResourcesVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/day-day-living': {
      id: '/support/day-day-living'
      path: '/support/day-day-living'
      fullPath: '/support/day-day-living'
      preLoaderRoute: typeof SupportDayDayLivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/newly-diagnosed': {
      id: '/support/newly-diagnosed'
      path: '/support/newly-diagnosed'
      fullPath: '/support/newly-diagnosed'
      preLoaderRoute: typeof SupportNewlyDiagnosedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/our-community': {
      id: '/support/our-community'
      path: '/support/our-community'
      fullPath: '/support/our-community'
      preLoaderRoute: typeof SupportOurCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-inquiry/the-infected-blood-inquiry/': {
      id: '/public-inquiry/the-infected-blood-inquiry/'
      path: '/public-inquiry/the-infected-blood-inquiry'
      fullPath: '/public-inquiry/the-infected-blood-inquiry/'
      preLoaderRoute: typeof PublicInquiryTheInfectedBloodInquiryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-inquiry/the-infected-blood-inquiry/appg': {
      id: '/public-inquiry/the-infected-blood-inquiry/appg'
      path: '/public-inquiry/the-infected-blood-inquiry/appg'
      fullPath: '/public-inquiry/the-infected-blood-inquiry/appg'
      preLoaderRoute: typeof PublicInquiryTheInfectedBloodInquiryAppgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NewsRoute: NewsRoute,
  BleedingDisordersFaqsRoute: BleedingDisordersFaqsRoute,
  BleedingDisordersHaemophiliaRoute: BleedingDisordersHaemophiliaRoute,
  BleedingDisordersInhibitorsRoute: BleedingDisordersInhibitorsRoute,
  BleedingDisordersTreatmentCentresRoute:
    BleedingDisordersTreatmentCentresRoute,
  BleedingDisordersTreatmentTypesRoute: BleedingDisordersTreatmentTypesRoute,
  BleedingDisordersWomenWithBleedingDisordersRoute:
    BleedingDisordersWomenWithBleedingDisordersRoute,
  EventsCategoriesRoute: EventsCategoriesRoute,
  GetInvolvedFundraisingRoute: GetInvolvedFundraisingRoute,
  GetInvolvedJoinRoute: GetInvolvedJoinRoute,
  PublicInquiryInquiryNewsRoute: PublicInquiryInquiryNewsRoute,
  PublicInquirySupportRoute: PublicInquirySupportRoute,
  ResourcesExternalResourcesRoute: ResourcesExternalResourcesRoute,
  ResourcesGuidelinesRoute: ResourcesGuidelinesRoute,
  ResourcesPublicationsRoute: ResourcesPublicationsRoute,
  ResourcesVideosRoute: ResourcesVideosRoute,
  SupportDayDayLivingRoute: SupportDayDayLivingRoute,
  SupportNewlyDiagnosedRoute: SupportNewlyDiagnosedRoute,
  SupportOurCommunityRoute: SupportOurCommunityRoute,
  PublicInquiryTheInfectedBloodInquiryAppgRoute:
    PublicInquiryTheInfectedBloodInquiryAppgRoute,
  PublicInquiryTheInfectedBloodInquiryIndexRoute:
    PublicInquiryTheInfectedBloodInquiryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
