# Generated by Django 6.1.1 on 2026-09-14 08:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factors', '0001_initial'),
        ('hospitals', '0003_province_admin_state'),
        ('injections', '0002_injectionrecord_status'),
        ('patients', '0003_stock_and_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(blank=True, default='', max_length=64)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(choices=[('IU', 'IU'), ('mg', 'mg')], default='IU', max_length=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots_created', to=settings.AUTH_USER_MODEL)),
                ('factor_medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='factors.factormedicine')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factor_stock', to='hospitals.hospital')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'factor_stock',
                'ordering': ['hospital__name', 'factor_medicine__name', 'expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('stock_in', 'Stock in'), ('stock_out', 'Stock out'), ('adjustment', 'Adjustment'), ('injection', 'Given to patient'), ('reversal', 'Reversal')], max_length=20)),
                ('quantity_delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('injection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='injections.injectionrecord')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.factorstock')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='factorstock',
            index=models.Index(fields=['hospital', 'factor_medicine'], name='factor_stoc_hospita_0d8b84_idx'),
        ),
        migrations.AddConstraint(
            model_name='factorstock',
            constraint=models.UniqueConstraint(fields=('hospital', 'factor_medicine', 'batch_number'), name='uniq_stock_hospital_factor_batch'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='stock_movem_movemen_d2f919_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['patient', 'created_at'], name='stock_movem_patient_0b2aca_idx'),
        ),
    ]
