# Generated by Django 6.1.1 on 2026-09-14 10:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0001_initial'),
        ('stock', '0001_stock_and_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStockShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(blank=True, default='', max_length=64)),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('allocated_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(choices=[('IU', 'IU'), ('mg', 'mg')], default='IU', max_length=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_shipments_created', to=settings.AUTH_USER_MODEL)),
                ('factor_medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='global_shipments', to='factors.factormedicine')),
            ],
            options={
                'db_table': 'global_stock_shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='factorstock',
            name='global_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_lots', to='stock.globalstockshipment'),
        ),
    ]
