# Generated by Django 6.1.1 on 2026-09-14 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_stock_and_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('injection', 'Injection'), ('treatment', 'Treatment'), ('stock', 'Stock'), ('bleeding', 'Bleeding'), ('system', 'System'), ('event', 'Event')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('related_type', models.CharField(blank=True, max_length=40)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_notifications_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'is_read', 'created_at'], name='patient_not_patient_c25907_idx'), models.Index(fields=['patient', 'category'], name='patient_not_patient_6520a0_idx')],
            },
        ),
    ]
