# Generated by Django 6.0.7 on 2026-09-22 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injections', '0003_clinical_and_stock_updates'),
        ('notifications', '0001_clinical_and_stock_updates'),
        ('patients', '0005_treatment_plan_and_prescribed_factor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientnotification',
            name='category',
            field=models.CharField(choices=[('injection', 'Injection'), ('treatment', 'Treatment'), ('stock', 'Stock'), ('bleeding', 'Bleeding'), ('system', 'System'), ('event', 'Event'), ('profile', 'Profile'), ('document', 'Document'), ('insight', 'Insight'), ('schedule', 'Schedule'), ('admin', 'Admin'), ('backup', 'Backup')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(default='android', max_length=16)),
                ('app', models.CharField(default='patient', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_devices',
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('injection', 'Injection'), ('treatment', 'Treatment'), ('stock', 'Stock'), ('bleeding', 'Bleeding'), ('system', 'System'), ('event', 'Event'), ('profile', 'Profile'), ('document', 'Document'), ('insight', 'Insight'), ('schedule', 'Schedule'), ('admin', 'Admin'), ('backup', 'Backup')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('related_type', models.CharField(blank=True, max_length=40)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='admin_notif_recipie_d0b02b_idx')],
            },
        ),
        migrations.CreateModel(
            name='InjectionReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=32)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('injection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='injections.injectionrecord')),
            ],
            options={
                'db_table': 'injection_reminder_logs',
                'constraints': [models.UniqueConstraint(fields=('injection', 'slot'), name='uniq_injection_reminder_slot')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyInsightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_logs', to='patients.patient')),
            ],
            options={
                'db_table': 'monthly_insight_logs',
                'constraints': [models.UniqueConstraint(fields=('patient', 'year', 'month'), name='uniq_monthly_insight')],
            },
        ),
    ]
