# Generated by Django 6.0.7 on 2026-09-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_activity_and_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='category',
            field=models.CharField(choices=[('injection', 'Injection'), ('treatment', 'Treatment'), ('stock', 'Stock'), ('bleeding', 'Bleeding'), ('system', 'System'), ('event', 'Event'), ('profile', 'Profile'), ('document', 'Document'), ('insight', 'Insight'), ('schedule', 'Schedule'), ('admin', 'Admin'), ('backup', 'Backup'), ('appointment', 'Appointment')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patientnotification',
            name='category',
            field=models.CharField(choices=[('injection', 'Injection'), ('treatment', 'Treatment'), ('stock', 'Stock'), ('bleeding', 'Bleeding'), ('system', 'System'), ('event', 'Event'), ('profile', 'Profile'), ('document', 'Document'), ('insight', 'Insight'), ('schedule', 'Schedule'), ('admin', 'Admin'), ('backup', 'Backup'), ('appointment', 'Appointment')], db_index=True, max_length=20),
        ),
    ]
