# Generated by Django 6.0.7 on 2026-09-22 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0003_province_admin_state'),
        ('patients', '0005_treatment_plan_and_prescribed_factor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_type', models.CharField(choices=[('clinic_review', 'Clinic review'), ('prophylaxis', 'Prophylaxis visit'), ('bleed_followup', 'Bleed follow-up'), ('physiotherapy', 'Physiotherapy'), ('dental', 'Dental planning'), ('counselling', 'Counselling'), ('other', 'Other')], default='clinic_review', max_length=32)),
                ('reason', models.TextField()),
                ('preferred_at', models.DateTimeField()),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=20)),
                ('patient_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_handled', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-preferred_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=32)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='appointments.appointment')),
            ],
            options={
                'db_table': 'appointment_reminder_logs',
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital', 'status'], name='appointment_hospita_ab3622_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='appointment_patient_6fe260_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentreminderlog',
            constraint=models.UniqueConstraint(fields=('appointment', 'slot'), name='uniq_appointment_reminder_slot'),
        ),
    ]
