# Generated by Django 6.1.1 on 2026-09-24 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_treatment_plan_and_prescribed_factor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('patient', 'Patient'), ('staff', 'Admin / staff'), ('injection', 'Injection'), ('treatment', 'Treatment'), ('bleeding', 'Bleeding episode')], max_length=20)),
                ('target_id', models.PositiveBigIntegerField()),
                ('body', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_notes', to='patients.patient')),
            ],
            options={
                'db_table': 'record_notes',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['target_type', 'target_id', '-created_at'], name='notes_target_idx'), models.Index(fields=['patient', '-created_at'], name='notes_patient_idx')],
            },
        ),
    ]
