"""Demo seed definitions for NHMS admin panel and patient app."""

from apps.accounts.rbac import (
    PERM_DOCUMENTS_ADD,
    PERM_INJECTIONS_ADD,
    PERM_INJECTIONS_VIEW,
    PERM_PATIENTS_CREATE,
    PERM_PATIENTS_UPDATE,
    PERM_PATIENTS_VIEW,
    PERM_STOCK_MANAGE,
    PERM_STOCK_VIEW,
    PERM_TREATMENTS_ADD,
    PERM_TREATMENTS_VIEW,
)

DEMO_MARKER = "NHMS_DEMO_SEED"
DEMO_PASSWORD = "DemoPass#2026"

CENTER_ADMINS = [
    {
        "username": "ravi.center",
        "email": "ravi.shrestha@hemophilia.org.np",
        "fullName": "Ravi Shrestha",
        "phone": "9841234567",
        "hospital": "Kathmandu Hemophilia Center",
        "dateOfBirth": "1982-04-12",
        "gender": "Male",
        "designation": "Center Administrator",
        "employeeId": "NHMS-CA-001",
        "nationalId": "123-456-78901",
        "officeAddress": "Maharajgunj, Kathmandu 44600",
        "permissions": None,
        "viewOnly": False,
    },
    {
        "fullName": "Nabin Karki",
        "email": "nabin.karki@hemophilia.org.np",
        "phone": "9841201001",
        "hospital": "TU Teaching Hospital",
        "dateOfBirth": "1979-08-03",
        "gender": "Male",
        "designation": "Hemophilia Center Lead",
        "employeeId": "NHMS-CA-002",
        "nationalId": "223-111-22001",
        "officeAddress": "Maharajgunj, Kathmandu",
    },
    {
        "fullName": "Sunita Gurung",
        "email": "sunita.gurung@hemophilia.org.np",
        "phone": "9841201002",
        "hospital": "Pokhara Hemophilia Center",
        "dateOfBirth": "1985-01-19",
        "gender": "Female",
        "designation": "Center Administrator",
        "employeeId": "NHMS-CA-003",
        "nationalId": "323-222-33002",
        "officeAddress": "Prithvi Chowk, Pokhara",
    },
    {
        "fullName": "Rajesh Yadav",
        "email": "rajesh.yadav@hemophilia.org.np",
        "phone": "9841201003",
        "hospital": "Biratnagar Hemophilia Center",
        "dateOfBirth": "1980-11-27",
        "gender": "Male",
        "designation": "Center Administrator",
        "employeeId": "NHMS-CA-004",
        "nationalId": "423-333-44003",
        "officeAddress": "Biratnagar-10, Morang",
    },
    {
        "fullName": "Mohan Pandey",
        "email": "mohan.pandey@hemophilia.org.np",
        "phone": "9841201004",
        "hospital": "Butwal Treatment Center",
        "dateOfBirth": "1983-06-15",
        "gender": "Male",
        "designation": "Center Administrator",
        "employeeId": "NHMS-CA-005",
        "nationalId": "523-444-55004",
        "officeAddress": "Butwal, Rupandehi",
    },
    {
        "fullName": "Anita Thapa",
        "email": "anita.thapa@hemophilia.org.np",
        "phone": "9841201005",
        "hospital": "Nepalgunj Hemophilia Center",
        "dateOfBirth": "1987-02-08",
        "gender": "Female",
        "designation": "Center Administrator",
        "employeeId": "NHMS-CA-006",
        "nationalId": "623-555-66005",
        "officeAddress": "Nepalgunj, Banke",
    },
    {
        "fullName": "Bikash Oli",
        "email": "bikash.oli@hemophilia.org.np",
        "phone": "9841201006",
        "hospital": "Dhangadhi Hemophilia Center",
        "dateOfBirth": "1981-09-22",
        "gender": "Male",
        "designation": "Center Administrator",
        "employeeId": "NHMS-CA-007",
        "nationalId": "723-666-77006",
        "officeAddress": "Dhangadhi, Kailali",
    },
]

TREATMENT_ADMINS = [
    {
        "username": "sita.treatment",
        "email": "sita.magar@hemophilia.org.np",
        "fullName": "Sita Magar",
        "phone": "9842345678",
        "hospital": "TU Teaching Hospital",
        "dateOfBirth": "1990-05-14",
        "gender": "Female",
        "designation": "Senior Treatment Coordinator",
        "employeeId": "NHMS-TA-001",
        "permissions": None,
        "viewOnly": False,
        "accessLabel": "Full treatment access",
    },
    {
        "fullName": "Pooja Tamang",
        "email": "pooja.tamang@hemophilia.org.np",
        "phone": "9842302001",
        "hospital": "Kathmandu Hemophilia Center",
        "dateOfBirth": "1992-03-11",
        "gender": "Female",
        "designation": "Treatment Nurse",
        "employeeId": "NHMS-TA-002",
        "permissions": None,
        "viewOnly": False,
        "accessLabel": "Full access (Kathmandu)",
    },
    {
        "fullName": "Kiran Shahi",
        "email": "kiran.shahi@hemophilia.org.np",
        "phone": "9842302002",
        "hospital": "Kathmandu Hemophilia Center",
        "dateOfBirth": "1988-12-02",
        "gender": "Male",
        "designation": "Clinical Records Officer",
        "employeeId": "NHMS-TA-003",
        "permissions": None,
        "viewOnly": True,
        "accessLabel": "View-only (Kathmandu)",
    },
    {
        "fullName": "Ajay Basnet",
        "email": "ajay.basnet@hemophilia.org.np",
        "phone": "9842302003",
        "hospital": "TU Teaching Hospital",
        "dateOfBirth": "1991-07-25",
        "gender": "Male",
        "designation": "Injection Desk Officer",
        "employeeId": "NHMS-TA-004",
        "permissions": [
            PERM_PATIENTS_VIEW,
            PERM_PATIENTS_UPDATE,
            PERM_INJECTIONS_VIEW,
            PERM_INJECTIONS_ADD,
        ],
        "viewOnly": False,
        "accessLabel": "Patients + injections only",
    },
    {
        "fullName": "Reena Shrestha",
        "email": "reena.shrestha@hemophilia.org.np",
        "phone": "9842302004",
        "hospital": "Pokhara Hemophilia Center",
        "dateOfBirth": "1993-01-30",
        "gender": "Female",
        "designation": "Pharmacy & Stock Officer",
        "employeeId": "NHMS-TA-005",
        "permissions": [
            PERM_PATIENTS_VIEW,
            PERM_STOCK_VIEW,
            PERM_STOCK_MANAGE,
        ],
        "viewOnly": False,
        "accessLabel": "Stock management focus",
    },
    {
        "fullName": "Deepak KC",
        "email": "deepak.kc@hemophilia.org.np",
        "phone": "9842302005",
        "hospital": "Biratnagar Hemophilia Center",
        "dateOfBirth": "1989-10-18",
        "gender": "Male",
        "designation": "Treatment Coordinator",
        "employeeId": "NHMS-TA-006",
        "permissions": [
            PERM_PATIENTS_VIEW,
            PERM_TREATMENTS_VIEW,
            PERM_TREATMENTS_ADD,
            PERM_INJECTIONS_VIEW,
        ],
        "viewOnly": False,
        "accessLabel": "Treatments focus",
    },
    {
        "fullName": "Sarita Nepal",
        "email": "sarita.nepal@hemophilia.org.np",
        "phone": "9842302006",
        "hospital": "Lalitpur Hemophilia Clinic",
        "dateOfBirth": "1994-04-07",
        "gender": "Female",
        "designation": "Documentation Officer",
        "employeeId": "NHMS-TA-007",
        "permissions": [
            PERM_PATIENTS_VIEW,
            PERM_DOCUMENTS_ADD,
        ],
        "viewOnly": False,
        "accessLabel": "Documents + patient view",
    },
    {
        "fullName": "Hari Poudel",
        "email": "hari.poudel@hemophilia.org.np",
        "phone": "9842302007",
        "hospital": "Hetauda Hemophilia Center",
        "dateOfBirth": "1986-08-21",
        "gender": "Male",
        "designation": "Clinical Assistant",
        "employeeId": "NHMS-TA-008",
        "permissions": [PERM_PATIENTS_VIEW, PERM_INJECTIONS_VIEW],
        "viewOnly": False,
        "accessLabel": "Read patients & injections",
    },
    {
        "fullName": "Gita Thapa",
        "email": "gita.thapa@hemophilia.org.np",
        "phone": "9842302008",
        "hospital": "Surkhet Hemophilia Center",
        "dateOfBirth": "1995-06-09",
        "gender": "Female",
        "designation": "Audit Support Officer",
        "employeeId": "NHMS-TA-009",
        "permissions": None,
        "viewOnly": True,
        "accessLabel": "View-only (Surkhet)",
    },
    {
        "fullName": "Suresh Chaudhary",
        "email": "suresh.chaudhary@hemophilia.org.np",
        "phone": "9842302009",
        "hospital": "Butwal Treatment Center",
        "dateOfBirth": "1987-11-03",
        "gender": "Male",
        "designation": "Treatment Admin",
        "employeeId": "NHMS-TA-010",
        "permissions": [
            PERM_PATIENTS_VIEW,
            PERM_PATIENTS_CREATE,
            PERM_PATIENTS_UPDATE,
            PERM_INJECTIONS_VIEW,
            PERM_INJECTIONS_ADD,
            PERM_TREATMENTS_VIEW,
            PERM_TREATMENTS_ADD,
        ],
        "viewOnly": False,
        "accessLabel": "Clinical ops (no stock manage)",
    },
]

PATIENTS = [
    {
        "fullName": "Arjun Thapa",
        "email": "demo.patient01@hemophilia.org.np",
        "mobile": "9811000001",
        "gender": "Male",
        "dob": "2010-03-15",
        "province": "Bagmati",
        "district": "Kathmandu",
        "localLevel": "Kathmandu Metropolitan City",
        "ward": 5,
        "address": "Baluwatar, Kathmandu",
        "bloodGroup": "O+",
        "hemophiliaType": "A",
        "severity": "Severe",
        "baseline": "1.20",
        "inhibitor": "None",
        "plan": "Regular Prophylaxis",
        "factor": "Factor VIII Concentrate (Recombinant)",
        "hospital": "Kathmandu Hemophilia Center",
    },
    {
        "fullName": "Maya Gurung",
        "email": "demo.patient02@hemophilia.org.np",
        "mobile": "9811000002",
        "gender": "Female",
        "dob": "2008-07-22",
        "province": "Gandaki",
        "district": "Kaski",
        "localLevel": "Pokhara Metropolitan City",
        "ward": 8,
        "address": "Chipledhunga, Pokhara",
        "bloodGroup": "A+",
        "hemophiliaType": "A",
        "severity": "Moderate",
        "baseline": "8.50",
        "inhibitor": "None",
        "plan": "On-demand",
        "factor": "Factor VIII Concentrate (Plasma-derived)",
        "hospital": "Pokhara Hemophilia Center",
    },
    {
        "fullName": "Bikash Rai",
        "email": "demo.patient03@hemophilia.org.np",
        "mobile": "9811000003",
        "gender": "Male",
        "dob": "2012-01-09",
        "province": "Koshi",
        "district": "Morang",
        "localLevel": "Biratnagar Metropolitan City",
        "ward": 3,
        "address": "Biratnagar-3, Morang",
        "bloodGroup": "B+",
        "hemophiliaType": "A",
        "severity": "Severe",
        "baseline": "0.80",
        "inhibitor": "Past",
        "plan": "ITI",
        "factor": "Factor VIII Concentrate (Recombinant)",
        "hospital": "Biratnagar Hemophilia Center",
    },
    {
        "fullName": "Sunita Yadav",
        "email": "demo.patient04@hemophilia.org.np",
        "mobile": "9811000004",
        "gender": "Female",
        "dob": "2005-11-30",
        "province": "Madhesh",
        "district": "Dhanusha",
        "localLevel": "Janakpur Sub-Metropolitan City",
        "ward": 6,
        "address": "Janakpur, Dhanusha",
        "bloodGroup": "AB+",
        "hemophiliaType": "A",
        "severity": "Mild",
        "baseline": "12.00",
        "inhibitor": "None",
        "plan": "On-demand",
        "factor": "Factor VIII Concentrate (Plasma-derived)",
        "hospital": "Janakpur Hemophilia Clinic",
    },
    {
        "fullName": "Rohan Karki",
        "email": "demo.patient05@hemophilia.org.np",
        "mobile": "9811000005",
        "gender": "Male",
        "dob": "2014-05-18",
        "province": "Bagmati",
        "district": "Lalitpur",
        "localLevel": "Lalitpur Metropolitan City",
        "ward": 4,
        "address": "Pulchowk, Lalitpur",
        "bloodGroup": "O+",
        "hemophiliaType": "B",
        "severity": "Severe",
        "baseline": "1.00",
        "inhibitor": "None",
        "plan": "Regular Prophylaxis",
        "factor": "Factor IX Concentrate (Recombinant)",
        "hospital": "Lalitpur Hemophilia Clinic",
    },
    {
        "fullName": "Anita Sharma",
        "email": "demo.patient06@hemophilia.org.np",
        "mobile": "9811000006",
        "gender": "Female",
        "dob": "2003-09-02",
        "province": "Bagmati",
        "district": "Kathmandu",
        "localLevel": "Kathmandu Metropolitan City",
        "ward": 10,
        "address": "Koteshwor, Kathmandu",
        "bloodGroup": "A+",
        "hemophiliaType": "A",
        "severity": "Moderate",
        "baseline": "6.75",
        "inhibitor": "None",
        "plan": "Regular Prophylaxis",
        "factor": "Factor VIII Concentrate (Recombinant)",
        "hospital": "TU Teaching Hospital",
    },
    {
        "fullName": "Prakash Oli",
        "email": "demo.patient07@hemophilia.org.np",
        "mobile": "9811000007",
        "gender": "Male",
        "dob": "2011-12-25",
        "province": "Sudurpashchim",
        "district": "Kailali",
        "localLevel": "Dhangadhi Sub-Metropolitan City",
        "ward": 2,
        "address": "Dhangadhi, Kailali",
        "bloodGroup": "B+",
        "hemophiliaType": "A",
        "severity": "Severe",
        "baseline": "1.50",
        "inhibitor": "Current",
        "plan": "Bypassing / Specialist",
        "factor": "Emicizumab",
        "hospital": "Dhangadhi Hemophilia Center",
    },
    {
        "fullName": "Kamala Bhandari",
        "email": "demo.patient08@hemophilia.org.np",
        "mobile": "9811000008",
        "gender": "Female",
        "dob": "2007-04-14",
        "province": "Lumbini",
        "district": "Rupandehi",
        "localLevel": "Butwal Sub-Metropolitan City",
        "ward": 7,
        "address": "Butwal, Rupandehi",
        "bloodGroup": "O-",
        "hemophiliaType": "B",
        "severity": "Moderate",
        "baseline": "7.25",
        "inhibitor": "None",
        "plan": "On-demand",
        "factor": "Factor IX Concentrate (Plasma-derived)",
        "hospital": "Butwal Treatment Center",
    },
    {
        "fullName": "Sanjay Maharjan",
        "email": "demo.patient09@hemophilia.org.np",
        "mobile": "9811000009",
        "gender": "Male",
        "dob": "2009-08-07",
        "province": "Bagmati",
        "district": "Bhaktapur",
        "localLevel": "Bhaktapur Municipality",
        "ward": 5,
        "address": "Suryabinayak, Bhaktapur",
        "bloodGroup": "A-",
        "hemophiliaType": "A",
        "severity": "Severe",
        "baseline": "2.10",
        "inhibitor": "None",
        "plan": "Regular Prophylaxis",
        "factor": "Factor VIII Concentrate (Plasma-derived)",
        "hospital": "Bhaktapur Treatment Center",
    },
    {
        "fullName": "Laxmi Poudel",
        "email": "demo.patient10@hemophilia.org.np",
        "mobile": "9811000010",
        "gender": "Female",
        "dob": "2013-02-28",
        "province": "Lumbini",
        "district": "Banke",
        "localLevel": "Nepalgunj Sub-Metropolitan City",
        "ward": 9,
        "address": "Nepalgunj, Banke",
        "bloodGroup": "B+",
        "hemophiliaType": "A",
        "severity": "Severe",
        "baseline": "0.95",
        "inhibitor": "None",
        "plan": "Regular Prophylaxis",
        "factor": "Factor VIII Concentrate (Recombinant)",
        "hospital": "Nepalgunj Hemophilia Center",
    },
    {
        "fullName": "Niraj Tamang",
        "email": "demo.patient11@hemophilia.org.np",
        "mobile": "9811000011",
        "gender": "Male",
        "dob": "2006-06-11",
        "province": "Bagmati",
        "district": "Makwanpur",
        "localLevel": "Hetauda Sub-Metropolitan City",
        "ward": 4,
        "address": "Hetauda, Makwanpur",
        "bloodGroup": "O+",
        "hemophiliaType": "B",
        "severity": "Mild",
        "baseline": "15.00",
        "inhibitor": "None",
        "plan": "On-demand",
        "factor": "Factor IX Concentrate (Recombinant)",
        "hospital": "Hetauda Hemophilia Center",
    },
    {
        "fullName": "Puja Adhikari",
        "email": "demo.patient12@hemophilia.org.np",
        "mobile": "9811000012",
        "gender": "Female",
        "dob": "2015-10-03",
        "province": "Karnali",
        "district": "Surkhet",
        "localLevel": "Birendranagar Municipality",
        "ward": 6,
        "address": "Birendranagar, Surkhet",
        "bloodGroup": "AB-",
        "hemophiliaType": "A",
        "severity": "Moderate",
        "baseline": "9.00",
        "inhibitor": "None",
        "plan": "Regular Prophylaxis",
        "factor": "Factor VIII Concentrate (Plasma-derived)",
        "hospital": "Surkhet Hemophilia Center",
    },
    {
        "fullName": "Ramesh Chaudhary",
        "email": "demo.patient13@hemophilia.org.np",
        "mobile": "9811000013",
        "gender": "Male",
        "dob": "2004-01-20",
        "province": "Madhesh",
        "district": "Parsa",
        "localLevel": "Birgunj Metropolitan City",
        "ward": 11,
        "address": "Birgunj, Parsa",
        "bloodGroup": "B+",
        "hemophiliaType": "B",
        "severity": "Severe",
        "baseline": "1.80",
        "inhibitor": "Past",
        "plan": "ITI",
        "factor": "Factor IX Concentrate (Recombinant)",
        "hospital": "Janakpur Hemophilia Clinic",
    },
    {
        "fullName": "Sangita Limbu",
        "email": "demo.patient14@hemophilia.org.np",
        "mobile": "9811000014",
        "gender": "Female",
        "dob": "2010-07-08",
        "province": "Koshi",
        "district": "Jhapa",
        "localLevel": "Bhadrapur Municipality",
        "ward": 3,
        "address": "Bhadrapur, Jhapa",
        "bloodGroup": "A+",
        "hemophiliaType": "A",
        "severity": "Mild",
        "baseline": "18.50",
        "inhibitor": "None",
        "plan": "On-demand",
        "factor": "Factor VIII Concentrate (Plasma-derived)",
        "hospital": "Biratnagar Hemophilia Center",
    },
    {
        "fullName": "Dipesh Khatri",
        "email": "demo.patient15@hemophilia.org.np",
        "mobile": "9811000015",
        "gender": "Male",
        "dob": "2002-12-12",
        "province": "Gandaki",
        "district": "Tanahu",
        "localLevel": "Bhanu Municipality",
        "ward": 2,
        "address": "Damauli area, Tanahu",
        "bloodGroup": "O+",
        "hemophiliaType": "A",
        "severity": "Severe",
        "baseline": "0.60",
        "inhibitor": "Current",
        "plan": "Bypassing / Specialist",
        "factor": "FEIBA",
        "hospital": "Pokhara Hemophilia Center",
    },
    {
        "fullName": "Rekha Basnet",
        "email": "demo.patient16@hemophilia.org.np",
        "mobile": "9811000016",
        "gender": "Female",
        "dob": "2008-03-27",
        "province": "Bagmati",
        "district": "Chitwan",
        "localLevel": "Bharatpur Metropolitan City",
        "ward": 8,
        "address": "Bharatpur, Chitwan",
        "bloodGroup": "A+",
        "hemophiliaType": "B",
        "severity": "Moderate",
        "baseline": "5.40",
        "inhibitor": "None",
        "plan": "Regular Prophylaxis",
        "factor": "Factor IX Concentrate (Plasma-derived)",
        "hospital": "Hetauda Hemophilia Center",
    },
    {
        "fullName": "Manish Shrestha",
        "email": "demo.patient17@hemophilia.org.np",
        "mobile": "9811000017",
        "gender": "Male",
        "dob": "2016-09-19",
        "province": "Lumbini",
        "district": "Dang",
        "localLevel": "Ghorahi Sub-Metropolitan City",
        "ward": 5,
        "address": "Ghorahi, Dang",
        "bloodGroup": "B+",
        "hemophiliaType": "A",
        "severity": "Severe",
        "baseline": "1.10",
        "inhibitor": "None",
        "plan": "Regular Prophylaxis",
        "factor": "Factor VIII Concentrate (Recombinant)",
        "hospital": "Butwal Treatment Center",
    },
    {
        "fullName": "Geeta Rana",
        "email": "demo.patient18@hemophilia.org.np",
        "mobile": "9811000018",
        "gender": "Female",
        "dob": "2001-05-05",
        "province": "Sudurpashchim",
        "district": "Kanchanpur",
        "localLevel": "Bhimdatta Municipality",
        "ward": 7,
        "address": "Mahendranagar, Kanchanpur",
        "bloodGroup": "O+",
        "hemophiliaType": "A",
        "severity": "Moderate",
        "baseline": "10.25",
        "inhibitor": "None",
        "plan": "On-demand",
        "factor": "Factor VIII Concentrate (Plasma-derived)",
        "hospital": "Dhangadhi Hemophilia Center",
    },
    {
        "fullName": "Bijay Malla",
        "email": "demo.patient19@hemophilia.org.np",
        "mobile": "9811000019",
        "gender": "Male",
        "dob": "2009-04-01",
        "province": "Karnali",
        "district": "Jumla",
        "localLevel": "Chandannath Municipality",
        "ward": 1,
        "address": "Khalanga, Jumla",
        "bloodGroup": "AB+",
        "hemophiliaType": "B",
        "severity": "Severe",
        "baseline": "2.00",
        "inhibitor": "None",
        "plan": "Regular Prophylaxis",
        "factor": "Factor IX Concentrate (Recombinant)",
        "hospital": "Surkhet Hemophilia Center",
    },
    {
        "fullName": "Sabina Koirala",
        "email": "demo.patient20@hemophilia.org.np",
        "mobile": "9811000020",
        "gender": "Female",
        "dob": "2012-11-16",
        "province": "Bagmati",
        "district": "Kathmandu",
        "localLevel": "Kathmandu Metropolitan City",
        "ward": 15,
        "address": "Kalanki, Kathmandu",
        "bloodGroup": "A+",
        "hemophiliaType": "A",
        "severity": "Severe",
        "baseline": "1.35",
        "inhibitor": "None",
        "plan": "Regular Prophylaxis",
        "factor": "Emicizumab",
        "hospital": "Kathmandu Hemophilia Center",
    },
]
