# Generated by Django 6.0.7 on 2026-09-17 04:48

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(max_length=240)),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('treatment', 'Treatment & Health Management'), ('education', 'Education & Awareness'), ('support', 'Support & Community'), ('more', 'More Services')], max_length=20)),
                ('icon_set', models.CharField(default='ion', max_length=8)),
                ('icon_name', models.CharField(default='medkit-outline', max_length=64)),
                ('action_type', models.CharField(choices=[('content', 'Detail page'), ('app_screen', 'Open app screen'), ('url', 'External link'), ('news', 'News list'), ('events', 'Events list'), ('resources', 'Resources list'), ('gallery', 'Gallery')], default='content', max_length=20)),
                ('action_value', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'cms_app_services',
                'ordering': ['category', 'sort_order', 'title'],
            },
            bases=(models.Model, apps.core.models.AuditMixin),
        ),
        migrations.CreateModel(
            name='CmsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('news', 'News & Notices'), ('event', 'Event'), ('resource', 'Resource / Download'), ('gallery', 'Gallery')], max_length=20)),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=400)),
                ('body', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'cms_articles',
                'ordering': ['-starts_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'slug'), name='cms_article_kind_slug_unique')],
            },
            bases=(models.Model, apps.core.models.AuditMixin),
        ),
    ]
