# Generated by Django 6.1.1 on 2026-09-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('factor_type', models.CharField(choices=[('FVIII', 'Factor VIII'), ('FIX', 'Factor IX'), ('Bypassing', 'Bypassing agent'), ('Other', 'Other')], max_length=20)),
                ('applicable_type', models.CharField(choices=[('A', 'Hemophilia A'), ('B', 'Hemophilia B'), ('Both', 'Both')], max_length=10)),
                ('unit', models.CharField(choices=[('IU', 'IU'), ('mg', 'mg')], default='IU', max_length=10)),
                ('standard_dose_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'factors_medicines',
                'ordering': ['name'],
            },
        ),
    ]
