# Generated by Django 6.1.1 on 2026-09-06 10:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factors', '0001_initial'),
        ('hospitals', '0003_province_admin_state'),
        ('patients', '0002_patient_photo_patient_user_alter_patient_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor_type', models.CharField(choices=[('FVIII', 'Factor VIII'), ('FIX', 'Factor IX'), ('Bypassing', 'Bypassing agent'), ('Other', 'Other')], max_length=20)),
                ('dose', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(choices=[('IU', 'IU'), ('mg', 'mg')], max_length=10)),
                ('indication', models.CharField(choices=[('Prophylaxis', 'Prophylaxis'), ('On-demand', 'On-demand'), ('ITI', 'ITI'), ('Surgery', 'Surgery/Procedure'), ('Trauma', 'Trauma'), ('Other', 'Other')], max_length=30)),
                ('administered_at', models.DateTimeField(db_index=True)),
                ('batch_number', models.CharField(blank=True, max_length=64)),
                ('bleed_site', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('inhibitor_warning', models.BooleanField(default=False)),
                ('is_correction', models.BooleanField(default=False)),
                ('is_void', models.BooleanField(default=False)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='injections_administered', to=settings.AUTH_USER_MODEL)),
                ('corrects_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='injections.injectionrecord')),
                ('factor_medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='injections', to='factors.factormedicine')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='injections', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='injections', to='patients.patient')),
            ],
            options={
                'db_table': 'injection_records',
                'ordering': ['-administered_at'],
                'indexes': [models.Index(fields=['patient', 'administered_at'], name='injection_r_patient_a9b64f_idx'), models.Index(fields=['hospital', 'administered_at'], name='injection_r_hospita_c6d76f_idx'), models.Index(fields=['factor_type'], name='injection_r_factor__832b15_idx')],
            },
        ),
    ]
