# Generated by Django 6.1.1 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("injections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="injectionrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Scheduled", "Scheduled"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                db_index=True,
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="injectionrecord",
            index=models.Index(fields=["status"], name="injection_re_status_idx"),
        ),
    ]
