# Generated by Django 6.1.1 on 2026-09-14 10:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injections', '0002_injectionrecord_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='injectionrecord',
            new_name='injection_r_status_059df2_idx',
            old_name='injection_re_status_idx',
        ),
        migrations.AddField(
            model_name='injectionrecord',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='injectionrecord',
            name='dose',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='injectionrecord',
            name='indication',
            field=models.CharField(choices=[('Prophylaxis', 'Prophylaxis'), ('On-demand', 'On-demand'), ('ITI', 'ITI'), ('Surgery', 'Surgery/Procedure'), ('Trauma', 'Trauma'), ('Emergency', 'Emergency'), ('Other', 'Other')], max_length=30),
        ),
    ]
