# Generated by Django 6.1.1 on 2026-09-06 05:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('provinces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_patient_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('local_level', models.CharField(max_length=255)),
                ('ward_number', models.PositiveSmallIntegerField()),
                ('address', models.TextField()),
                ('blood_group', models.CharField(max_length=5)),
                ('hemophilia_type', models.CharField(choices=[('A', 'Hemophilia A'), ('B', 'Hemophilia B')], max_length=5)),
                ('deficient_factor', models.CharField(max_length=10)),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=20)),
                ('baseline_factor_level', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('inhibitor_status', models.CharField(choices=[('None', 'None'), ('Past', 'Past'), ('Current', 'Current')], default='None', max_length=20)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=80)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Rejected', 'Rejected')], db_index=True, default='Active', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='provinces.district')),
                ('primary_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_patients', to='hospitals.hospital')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='provinces.province')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hemophilia_type'], name='patients_hemophi_bebfab_idx'), models.Index(fields=['severity'], name='patients_severit_f708fd_idx'), models.Index(fields=['province'], name='patients_provinc_42ce21_idx')],
            },
        ),
    ]
