# Generated by Django 6.1.1 on 2026-09-14 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_province_admin_state'),
        ('patients', '0002_patient_photo_patient_user_alter_patient_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_documents', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
