# Generated by Django 6.1.1 on 2026-09-14 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_province_admin_state'),
        ('patients', '0003_stock_and_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BleedingEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_date', models.DateField(db_index=True)),
                ('site', models.CharField(blank=True, max_length=128)),
                ('severity', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bleeding_episodes', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bleeding_episodes', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bleeding_episodes_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bleeding_episodes',
                'ordering': ['-episode_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'episode_date'], name='bleeding_ep_patient_aba8c9_idx')],
            },
        ),
    ]
