# Generated by Django 6.1.1 on 2026-09-14 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0001_initial'),
        ('patients', '0004_clinical_and_stock_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='prescribed_factor_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_patients', to='factors.factormedicine'),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_plan',
            field=models.CharField(choices=[('Regular Prophylaxis', 'Regular Prophylaxis'), ('On-demand', 'On-demand'), ('ITI', 'ITI'), ('Bypassing / Specialist', 'Bypassing / Specialist'), ('Other', 'Other')], default='Regular Prophylaxis', max_length=40),
        ),
    ]
