# Generated by Django 6.1.1 on 2026-09-06 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0003_province_admin_state'),
        ('injections', '0001_initial'),
        ('patients', '0002_patient_photo_patient_user_alter_patient_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment_type', models.CharField(choices=[('Physiotherapy', 'Physiotherapy'), ('Surgery', 'Surgery'), ('Admission', 'Admission'), ('ITI Program', 'ITI Program'), ('Counseling', 'Counseling'), ('Other', 'Other')], max_length=40)),
                ('description', models.TextField()),
                ('treatment_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'treatment_records',
                'ordering': ['-treatment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('injection', 'Injection'), ('treatment', 'Treatment')], max_length=20)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='hospitals.hospital')),
                ('injection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_log', to='injections.injectionrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_log', to='treatments.treatmentrecord')),
            ],
            options={
                'db_table': 'hospital_visits',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='treatmentrecord',
            index=models.Index(fields=['patient', 'treatment_date'], name='treatment_r_patient_ee6f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentrecord',
            index=models.Index(fields=['hospital', 'treatment_date'], name='treatment_r_hospita_bb6087_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalvisit',
            index=models.Index(fields=['patient', 'visit_date'], name='hospital_vi_patient_603a80_idx'),
        ),
    ]
